name: snakemake-msi-env

channels:
  - conda-forge
  - bioconda
  - nodefaults

dependencies:
  - python=3.12
  - black
  - isort
  - pylint
  - snakemake
  - snakefmt
  # - mason
  - varlociraptor
  # - curl
  # - interval-binning
  # - pysam
  - samtools
  # - bcftools