name: snakemake-msi-env

channels:
  - conda-forge
  - bioconda
  - nodefaults

dependencies:
  - python=3.12
  - black
  - isort
  - pylint
  - snakemake
  - snakefmt
  - mason
  # - curl
  - interval-binning
  - trf
  - pysam
  - samtools
  - bcftools